import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rubrr.s3-main.oktopod.app/');
  await expect(page.getByRole('link', { name: 'RUBRR' })).toBeVisible();
  await page.getByRole('link', { name: '✨ Plus de 712 questions' }).click();
  await expect(page.getByRole('heading', { name: 'Toutes les questions' })).toBeVisible();
  await page.getByRole('textbox').click();
  await page.getByRole('button', { name: 'Rechercher' }).click();
  await expect(page.getByRole('columnheader', { name: 'Question' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Tags' })).toBeVisible();
  await expect(page.getByRole('rowheader', { name: 'Quelles sont les bonnes' })).toBeVisible();
  await expect(page.getByRole('row', { name: 'Quelles sont les bonnes' }).getByRole('cell').first()).toBeVisible();
  await expect(page.getByRole('row', { name: 'Quelles sont les bonnes' }).locator('span').first()).toBeVisible();
  await expect(page.getByRole('row', { name: 'Quelles sont les bonnes' }).locator('span').nth(1)).toBeVisible();
  await page.getByRole('row', { name: 'Quelles sont les bonnes' }).getByRole('link').click();
  await expect(page.getByRole('heading', { name: 'Quelles sont les bonnes' })).toBeVisible();
  await page.locator('.bg-blue-500').first().click();
  await page.locator('span:nth-child(2)').first().click();
  await expect(page.getByRole('heading', { name: 'Réponse du système :' })).toBeVisible();
  await expect(page.getByText('Mettre à jour les listes de')).toBeVisible();
  await expect(page.getByText('Réponse du système : Mettre')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Autres questions dans ce thème' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Question' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Tags' })).toBeVisible();
  await expect(page.getByRole('rowheader', { name: 'Quelles sont les bonnes' })).toBeVisible();
  await expect(page.getByRole('row', { name: 'Quelles sont les bonnes' }).getByRole('cell').first()).toBeVisible();
  await expect(page.getByRole('row', { name: 'Quelles sont les bonnes' }).getByRole('cell').nth(1)).toBeVisible();
  await page.getByRole('link', { name: 'Retour' }).click();
  await page.getByRole('link', { name: 'Retour' }).click();
  await expect(page.getByRole('heading', { name: 'Questions pour un CDA' })).toBeVisible();
  await expect(page.getByText('🎓 Pour vous assurer d\'être')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Backend' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Conception BDD' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Design Pattern' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'DevOps' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Docker' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Frontend' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Green It' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Html' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Javascript' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Micro Services' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Mise en place Server' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Multicouche' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'NoSql' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'POO' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'React' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'S.O.L.I.D' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'SEO' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Sql', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Sécurite' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Testing' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Uml' })).toBeVisible();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Réponse de test pour PlayWright');
  await page.getByRole('button', { name: 'Répondre' }).click();
  // await page.goto('https://rubrr.s3-main.oktopod.app/');
  // await page.getByRole('heading', { name: 'Résultat de la question :' }).click();
  // await expect(page.getByRole('heading', { name: 'Taux de réussite de cette' })).toBeVisible();
  // await page.getByText('Votre réponse est : Réponse corrigée ').click();
});